// Generated by CoffeeScript 1.8.0
(function() {
  var SkipEdge, SkipNode;

  SkipNode = (function() {
    function SkipNode() {
      this.right_edge = null;
      this.left_edge = null;
      this.down = null;
      this.element = null;
    }

    return SkipNode;

  })();

  SkipEdge = (function() {
    function SkipEdge(distance) {
      this.distance = distance;
      this.left_node = null;
      this.right_node = null;
    }

    return SkipEdge;

  })();

  module.exports = {
    SkipNode: SkipNode,
    SkipEdge: SkipEdge
  };

}).call(this);
