// Generated by CoffeeScript 1.8.0
(function() {
  var SkipEdge, SkipList, SkipNode, _ref;

  _ref = require('./nodes'), SkipNode = _ref.SkipNode, SkipEdge = _ref.SkipEdge;

  SkipList = (function() {
    function SkipList() {
      var first_edge, first_head;
      this.heads = [];
      first_head = new SkipNode();
      first_edge = new SkipEdge(0);
      first_edge.left_node = first_head;
      first_head.right_edge = first_edge;
      this.heads.push(first_head);
    }

    SkipList.prototype.insert = function(element) {};

    return SkipList;

  })();

  module.exports = {
    SkipList: SkipList
  };

}).call(this);
