// Generated by CoffeeScript 1.8.0
(function() {
  var SkipList;

  SkipList = (function() {
    function SkipList() {}

    return SkipList;

  })();

  module.exports = {
    SkipList: SkipList
  };

}).call(this);
