// Generated by CoffeeScript 1.8.0
(function() {
  var SkipList, assert;

  assert = require('assert');

  SkipList = require('../skip_list');

  describe('list_tests', function() {
    return describe('test insert', function() {});
  });

}).call(this);
