// Generated by CoffeeScript 1.8.0
(function() {
  var Element;

  Element = (function() {
    function Element(value) {
      this.value = value;
    }

    Element.prototype.compare = function(other) {
      if (this.value === other.value) {
        return 0;
      } else if (this.value < other.value) {
        return -1;
      } else if (this.value > other.value) {
        return 1;
      } else {
        throw Error("Unable to compare with this object");
      }
    };

    return Element;

  })();

  module.exports = {
    Element: Element
  };

}).call(this);
